<?php

namespace Database\Seeders;

use App\Models\Pegawai;
use Illuminate\Database\Seeder;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pegawai = [
            [
                'nama_depan' => 'John',
                'nama_belakang' => 'Doe',
                'tanggal_lahir' => '1980-05-15',
                'tanggal_masuk' => '2020-01-01',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Jendral Sudirman No. 123',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '12345',
                'nomor_telepon' => '08123456789',
                'email' => 'john.doe@example.com',
                'id_departemen' => 1,
                'id_jabatan' => 1,
            ],
            [
                'nama_depan' => 'Jane',
                'nama_belakang' => 'Smith',
                'tanggal_lahir' => '1985-08-20',
                'tanggal_masuk' => '2019-06-15',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Thamrin No. 456',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '54321',
                'nomor_telepon' => '087654321',
                'email' => 'jane.smith@example.com',
                'id_departemen' => 2,
                'id_jabatan' => 2,
            ],
            [
                'nama_depan' => 'Michael',
                'nama_belakang' => 'Johnson',
                'tanggal_lahir' => '1992-02-10',
                'tanggal_masuk' => '2021-03-20',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Diponegoro No. 789',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '67890',
                'nomor_telepon' => '08111223344',
                'email' => 'michael.johnson@example.com',
                'id_departemen' => 1,
                'id_jabatan' => 3,
            ],
            [
                'nama_depan' => 'Emily',
                'nama_belakang' => 'Williams',
                'tanggal_lahir' => '1987-12-25',
                'tanggal_masuk' => '2018-04-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Pahlawan No. 321',
                'kota' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'kode_pos' => '45678',
                'nomor_telepon' => '08567890123',
                'email' => 'emily.williams@example.com',
                'id_departemen' => 3,
                'id_jabatan' => 2,
            ],
            [
                'nama_depan' => 'Daniel',
                'nama_belakang' => 'Brown',
                'tanggal_lahir' => '1990-06-18',
                'tanggal_masuk' => '2022-01-10',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Gajah Mada No. 555',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '98765',
                'nomor_telepon' => '08987654321',
                'email' => 'daniel.brown@example.com',
                'id_departemen' => 2,
                'id_jabatan' => 1,
            ],
            [
                'nama_depan' => 'John',
                'nama_belakang' => 'Doe',
                'tanggal_lahir' => '1980-05-15',
                'tanggal_masuk' => '2020-01-01',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Jendral Sudirman No. 123',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '12345',
                'nomor_telepon' => '08123456789',
                'email' => 'john2.doe@example.com',
                'id_departemen' => 1,
                'id_jabatan' => 1,
            ],
            [
                'nama_depan' => 'Jane',
                'nama_belakang' => 'Smith',
                'tanggal_lahir' => '1985-08-20',
                'tanggal_masuk' => '2019-06-15',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Thamrin No. 456',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '54321',
                'nomor_telepon' => '087654321',
                'email' => 'jane2.smith@example.com',
                'id_departemen' => 2,
                'id_jabatan' => 2,
            ],
            [
                'nama_depan' => 'Michael',
                'nama_belakang' => 'Johnson',
                'tanggal_lahir' => '1992-02-10',
                'tanggal_masuk' => '2021-03-20',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Diponegoro No. 789',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '67890',
                'nomor_telepon' => '08111223344',
                'email' => 'michael2.johnson@example.com',
                'id_departemen' => 1,
                'id_jabatan' => 3,
            ],
            [
                'nama_depan' => 'Emily',
                'nama_belakang' => 'Williams',
                'tanggal_lahir' => '1987-12-25',
                'tanggal_masuk' => '2018-04-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Pahlawan No. 321',
                'kota' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'kode_pos' => '45678',
                'nomor_telepon' => '08567890123',
                'email' => 'emily2.williams@example.com',
                'id_departemen' => 3,
                'id_jabatan' => 2,
            ],
            [
                'nama_depan' => 'Daniel',
                'nama_belakang' => 'Brown',
                'tanggal_lahir' => '1990-06-18',
                'tanggal_masuk' => '2022-01-10',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Gajah Mada No. 555',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '98765',
                'nomor_telepon' => '08987654321',
                'email' => 'daniel2.brown@example.com',
                'id_departemen' => 2,
                'id_jabatan' => 1,
            ],
            [
                'nama_depan' => 'John',
                'nama_belakang' => 'Doe',
                'tanggal_lahir' => '1980-05-15',
                'tanggal_masuk' => '2020-01-01',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Jendral Sudirman No. 123',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '12345',
                'nomor_telepon' => '08123456789',
                'email' => 'john3.doe@example.com',
                'id_departemen' => 1,
                'id_jabatan' => 1,
            ],
            [
                'nama_depan' => 'Jane',
                'nama_belakang' => 'Smith',
                'tanggal_lahir' => '1985-08-20',
                'tanggal_masuk' => '2019-06-15',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Thamrin No. 456',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '54321',
                'nomor_telepon' => '087654321',
                'email' => 'jane3.smith@example.com',
                'id_departemen' => 2,
                'id_jabatan' => 2,
            ],
            [
                'nama_depan' => 'Michael',
                'nama_belakang' => 'Johnson',
                'tanggal_lahir' => '1992-02-10',
                'tanggal_masuk' => '2021-03-20',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Diponegoro No. 789',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '67890',
                'nomor_telepon' => '08111223344',
                'email' => 'michael3.johnson@example.com',
                'id_departemen' => 1,
                'id_jabatan' => 3,
            ],
            [
                'nama_depan' => 'Emily',
                'nama_belakang' => 'Williams',
                'tanggal_lahir' => '1987-12-25',
                'tanggal_masuk' => '2018-04-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Pahlawan No. 321',
                'kota' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'kode_pos' => '45678',
                'nomor_telepon' => '08567890123',
                'email' => 'emily3.williams@example.com',
                'id_departemen' => 3,
                'id_jabatan' => 2,
            ],
            [
                'nama_depan' => 'Daniel',
                'nama_belakang' => 'Brown',
                'tanggal_lahir' => '1990-06-18',
                'tanggal_masuk' => '2022-01-10',
                'jenis_kelamin' => 'Laki',
                'alamat' => 'Jl. Gajah Mada No. 555',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '98765',
                'nomor_telepon' => '08987654321',
                'email' => 'daniel3.brown@example.com',
                'id_departemen' => 2,
                'id_jabatan' => 1,
            ],
        ];

        // Insert data pegawai ke dalam database
        foreach ($pegawai as $data) {
            Pegawai::create($data);
        }
    }
}
